SET IDENTITY_INSERT TB_RESPOSTA ON;
GO
INSERT INTO TB_RESPOSTA(Id_Resposta, Texto_Resposta) VALUES
(1,'Ser bem sucedido e obter um bom retorno financeiro'),
(2,'Trabalhar em algo que esteja em evidência no mercado'),
(3,'Trabalhar em algo que você goste'),
(4,'Obter um retorno financeiro '),
(5,' Poder ajudar ao próximo'),
(6,' Possui uma posição de destaque no mercado de trabalho.'),
(7,' É aventureira e viaja bastante'),
(8,' Curte a vida e está sempre descobrindo coisas novas'),
(9,' É bastante criativa e está sempre com novidades'),
(10,' Se dedica a algum trabalho de ajuda ao próximo'),
(11,' Uma empresa baseada no meu interesse pessoal'),
(12,' Uma empresa direcionada a algo evidente no mercado independente da aréa de atividade'),
(13,' Uma empresa onde eu pudesse trabalhar com meus amigos e familiares'),
(14,' Uma empresa tradicional, com produtos ou serviços de facil comercialização'),
(15,' Uma empresa criativa onde eu pudesse desenolver idéias inovadoras'),
(16,' Futebol'),
(17,' Artes Marciais'),
(18,' Natação'),
(19,' Tenis'),
(20,' Não gosto de esportes'),
(21,' Ficar em algum lugar isolado'),
(22,' Tentra se introduzir em um grupo'),
(23,' Curtir sozinho'),
(24,' Se socializar e conquistar amigos'),
(25,' Ir embora por estar sozinho'),
(26,' Bill Gates'),
(27,' Steve Jobs'),
(28,' Arnold Schwarzenegger'),
(29,' Brad Pitt'),
(30,' Tenzin Gyatso (Dalai Lama)'),
(31,' Possuem status e são influentes'),
(32,' Possuem interesses em comum comigo'),
(33,' Compartilham das mesmas ideias'),
(34,' São bastante diferentes de mim'),
(35,' Não me preocupo com caracteriscas quando procuro uma amizade'),
(36,' Ser um aluno dedicado e tirar boas notas'),
(37,' Ser atencioso e ajudar meus colegas'),
(38,' Ser bastante dedicado aos esportes'),
(39,' Não prestar atenção nas aulas e ser repreendido'),
(40,' Ser engraçado e contar piadas'),
(41,' Reformar uma casa'),
(42,' Me colocar em contato com pessoas bem-sucedidas'),
(43,' Realizar alguma atividade em equipe'),
(44,' Realizar uma atividade com boa remuneração'),
(45,' Realizar uma atividade volúntaria'),
(46,' Um jantar de comemoração com amigos e/ou familiares'),
(47,' Investiria no meu desenvolvimento profissional'),
(48,' Faria uma viagem'),
(49,' Gastaria o minimo possivel'),
(50,' Compraria algum produto caro de meu interesse'),
(51,' Uma empresa de internet'),
(52,' Uma fábrica de computadores'),
(53,' Um restaurante'),
(54,' Uma academia'),
(55,' Uma cliníca medica'),
(56,' Não ser bem sucedido profissionalmente'),
(57,' Nao me destacar no mercado de trabalho'),
(58,' Não construir uma familia'),
(59,' Não ter muito tempo para curtir a vida'),
(60,' Escolher a carreira errada e ter que mudar depois');
	
GO

SET IDENTITY_INSERT TB_RESPOSTA OFF;
GO