SET IDENTITY_INSERT TB_UNIDADE_DE_ENSINO ON;
GO

INSERT INTO TB_UNIDADE_DE_ENSINO(Id_Unidade_de_Ensino, Nome_Unidade_de_Ensino,Site_Unidade_de_Ensino,Id_Cidade,Endereco_Unidade_de_Ensino, Descricao_Unidade_de_Ensino) VALUES
(1,'INPG - Instituto Nacional de Pós Graduação','https://www.inpg.edu.br/',5270,'Avenida Nações Unidas, 12995 - Brooklin',''),
/*(2,'Universidade Michigan','https://www.inpg.edu.br/',5270,'Av. das Nações Unidas, 12551 - Brooklin'),*/
(3,'Uni São Paulo','http://www.unisaopaulo.com.br/',5270,'Rua Conde de Porto Alegre, 1913 - Campo Belo',''),
(4,'Centro Universitário Anhanguera - Campo Limpo','http://anhanguera.com/graduacao/localidades/spcampolimpo.php',5270,' Estrada do Campo Limpo, 3677 - Campo Limpo',''),
(5,'Faculdade Colégio Morumbi','http://morumbisul.com.br/',5270,'Rua Nsa Sra do Bom Conselho, 351 - Campo Limpo ',''),
(6,'Faculdade Horizontes - FH','http://www.faculdadehorizontes.com.br/',5270,'Rua Raul dos Santos Machado, 25 - Campo Limpo',''),
(7,'UNASP - SP','http://unasp-sp.edu.br/',5270,'Estrada Itapecerica, 5859 - Capão Redondo',''),
/*Todos os Campus Unisa já foram acrescentados, obs.:sem EAD*/
(8,'UNISA - Campus I - Interlagos','http://www.unisa.br',5270,'Rua Prof. Enéas de Siqueira Neto, 340 - Jardim das Imbuias',''),
(9,'UNISA - Campus II - Metrô Adolfo Pinheiro','http://www.unisa.br',5270,'Rua Isabel Schmidt, 349 - Santo Amaro',''),
(10,'UNISA - Campus III - Metrô Largo Treze','http://www.unisa.br',5270,'Rua Humboldt, 29  Santo Amaro',''),
(11,'UNISA -Campus IV - Metrô Marechal Deodoro','http://www.unisa.br',5270,'Rua Dr. Gabriel dos Santos, 30 - Santa Cecilia ',''),
/**/
(12,'Escola Dominicana de Teologia - EDT','',5270,'Rua São Daniel, 119 - Vila Brasilio Machado',''),
(13,'Organização Santamarense de Educação e Cultura (Osec) - Cursino','',5270,'Rua Santa Cruz, 1191',''),
(14,'Osec Organização Santamarense Educação Cultura (Osec) - Grajau','',5270,'Rua Henrique Muzzio, 152 - V Gumercindo',''),
(15,'Faculdade Teologia Nossa Senhora Assunção','',5270,'Avenida Nazaré, 993 - Ipiranga',''),
(16,'UNESP - Nead(Núcleo de Educação a Distância) - Ipiranga','https://edutec.unesp.br/index.php?lang=pt-br',5270,'Rua Dom Luís Lasagna, 400 - Ipiranga',''),
(17,'UniCristã - Universidade Cristã Livre','',5270,'Rua Agostinho Gomes, 2235 - Ipiranga,''',''),
(18,'UNIFAI - Centro Universitário Assunção','http://www.unifai.edu.br/',5270,'Rua Afonso Celso, 671 - Vila Mariana',''),
(19,'UNESP - Campus São Paulo - Ipiranga','http://www.unesp.br/',5270,'Rua Dom Luís Lasanha, 400 - Ipiranga',''),
(20,'FAMESP - Faculdade Método de São Paulo','http://famesp.com.br/',5270,'Avenida Jabaquara, 1314 - Mirandópolis',''),
/*Todos os polos UniCeu, obs.:http://portal.sme.prefeitura.sp.gov.br/polos */

(21,'UniCEU Vila do Sol','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Vila-do-Sol--Polo-Jd-angela',5270,'Avenida dos Funcionários Públicos, 367 ',''),
(22,'UniCEU Guarapiranga','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Guarapiranga',5270,' Estrada da Baronesa, 120 - Baronesa',''),
(23,'UniCEU Água Azul','http://portal.sme.prefeitura.sp.gov.br//Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-agua-Azul--Polo-Cidade-Tiradentes',5270,'Av. dos Metalúrgicos, 1.262 - Cidade Tiradentes',''),
(24,'UniCEU Alto Alegre','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Alto-Alegre',5270,'Rua Bento Guelfi, 1802 - Jardim da Laranjeira',''),
(25,'UniCEU Alvarenga ','http://portal.sme.prefeitura.sp.gov.br//Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Alvarenga--Polo-Balneario-Sao-Francisco',5270,'Estrada do Alvarenga, 3.752 - Pedreira',''),
(26,'UniCEU Aricanduva','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Aricanduva--Polo-Vila-Aricanduva',5270,'Rua Olga Fadel Abarca, s/n - Jardim Santa Terezinha',''),
(27,'UniCEU Azul da Cor do Mar','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Azul-da-Cor-do-Mar--Polo-Cidade-Antonio-E-de-Carvalho',5270,'Rua Ernesto de Souza Cruz, 211 – Cidade Antônio Estevão de Carvalho',''),
(28,'UniCEU Butantã','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Jd-Butanta--Polo-Jd-Esmeralda',5270,'Rua Eng. Heitor Ant. Eiras Garcia, 1.700/1.870 - Jardim Esmeralda',''),
(29,'UniCEU Caminho do Mar','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Caminho-do-Mar',5270,'Rua Eng. Armando de Arruda Pereira, 5.241 - Jabaquara',''),
(30,'UniCEU Campo Limpo','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Campo-Limpo--Polo-Pirajussara',5270,'Av. Carlos Lacerda, 678 - Pirajussara',''),
(31,'UniCEU Cantos do Amanhecer','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Cantos-do-Amanhecer',5270,'Avenida Cantos do Amanhecer, s/n - Jardim Eledy',''),
(32,'UniCEU Capão Redondo','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos-UniCEU-Capao-Redondo--Polo-Capao-Redondo',5270,'R. Daniel Gran, s/n - Capão Redondo',''),
(33,'UniCEU Casa Blanca','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Casa-Blanca--Polo-Vila-das-Belezas',5270,'R. João Damasceno, 85 - Jardim São Luís',''),
(34,'UniCEU Cidade Dutra','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Cidade-Dutra--Polo-Interlagos',5270,'Av. Interlagos, 7.350 - Interlagos',''),
(35,'UniCEU Feitiço da Vila','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Feitico-da-Vila',5270,'Rua Feitiço da Vila, 399 - Chácara Santa Maria',''),
(36,'UniCEU Formosa','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Formosa--Polo-Vila-Formosa',5270,'R. Sgt. Claudiner Evaristo Dias, 10 - Pq. Sto Antônio',''),
(37,'UniCEU Heliópolis','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Heliopolis',5270,'Estrada da Lágrimas, 2385 - São João Clímaco',''),
(38,'UniCEU Inácio Monteiro','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Inacio-Monteiro',5270,'Rua Barão Barroso do Amazonas, s/n - Conjunto Inácio Monteiro',''),
(39,'UniCEU Jaçanã','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Jacana--Polo-Jardim-Guapira',5270,'Rua Francisca Espósito Tonetti, 105 - Jaçanã',''),
(40,'UniCEU Jaguaré','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Jaguare',5270,'Av. Keikiti Simomoto, 80 - Jaguaré',''),
(41,'UniCEU Jambeiro','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Jambeiro--Polo-Jd-Moreno',5270,'Av. José Pinheiro Borges, 60 - Guaianases',''),
(42,'UniCEU Jardim Paulistano','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Jardim-Paulistano--Polo-Jd-Paulistano',5270,'R. Aparecida do Taboado, s/n - Jd. Paulistano',''),
(43,'UniCEU Lajeado','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Lajeado',5270,'Rua Manuel da Mota Coutinho, 293 - Guaianases',''),
(44,'UniCEU Meninos','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Meninos--Polo-Sao-Joao-Climaco',5270,'R. Barbinos, 111 - São João Clímaco',''),
(46,'UniCEU Navegantes','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Navegantes--Polo-Pq-Residencial-Cocaia',5270,'R. Maria Moassab Barbour, s/n - Pq. Residencial Cocaia ',''),
(47,'UniCEU Paraisópolis','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Paraisopolis--Polo-Paraisopolis',5270,'R. Dr. José Augusto S. e Silva, s/n - Pq. Jd. Morumbi',''),
(48,'UniCEU Parelheiros','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Parelheiros--Polo-Jd-Novo-Parelheiros',5270,'R. José Pedro de Borba, 20 - Parelheiros ',''),
(49,'UniCEU Parque Anhanguera','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Parque-Anhanguera',5270,' Rua Pedro José de Lima, 1020 - Jardim Anhanguera',''),
(50,'UniCEU Parque Bristol','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Parque-Bristol--Polo-Parque-Bristol',5270,'R. Professor Arthur Primavesi, s/n - Pq. Bristol',''),
(51,'UniCEU Parque São Carlos','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Parque-Sao-Carlos--Polo-Jd-Sao-Carlos',5270,'R. Clarear, 643 - Jd. São Carlos',''),
(52,'UniCEU Parque Veredas','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Parque-Veredas--Polo-Chacara-Dona-Olivia',5270,'R. Daniel Muller, 347 - Itaim Paulista ',''),
(53,'UniCEU Paz','',5270,'Rua Daniel Cerri, 1549 - Jardim Paraná',''),
(54,'UniCEU Pêra Marmelo ','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Pera-Marmelo--Polo-Jd-Sta-Lucrecia',5270,'R. Pera Marmelo, 226 - Jaraguá ',''),
(55,'UniCEU Perus','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Perus--Polo-Vila-Malvina',5270,'R. Bernardo José de Lorena, s/n - Vila Malvina',''),
(56,'UniCEU Quinta do Sol','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Quinta-do-Sol--Polo-Cangaiba',5270,'Av. Luiz Imparato, 564 - Pq. Císper',''),
(57,'UniCEU Rosa da China','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Rosa-da-China--Polo-Jd-Sao-Roberto',5270,'R. Clara Petrela, 113 - Jd. São Roberto',''),
(58,'UniCEU São Mateus','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Sao-Mateus--Polo-Pq-Boa-Esperanca',5270,'R. Curumatim, 201 - Pq. Boa Esperança',''),
(59,'UniCEU São Rafael','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Sao-Rafael--Polo-Jd-Promorar',5270,' R. Cinira Polônio, 100 - Conj. Promorar Rio Claro',''),
(60,'UniCEU Sapopemba','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Sapopemba',5270,'Rua Manuel Quirino de Mattos, s/n - Jardim Sapopemba',''),
(61,'UniCEU Tiquatira','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Tiquatira--Polo-Penha',5270,'Av. Cond. Elizabeth de Robiano com Rua Kampala - Penha',''),
(62,'UniCEU Três Lagos','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Tres-Lagos--Polo-Barro-Branco',5270,'Estrada do Barro Branco, s/n - Jd. Três Corações',''),
(63,'UniCEU Três Pontes','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Tres-Pontes',5270,'Rua Capachós, 400 - Jardim Célia',''),
(64,'UniCEU Uirapuru','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Uirapuru',5270,'Rua Nazir Miguel, 849 - Jardim Paulo VI',''),
(65,'UniCEU Vila Atlântica','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Vila-Atlantica--Polo-Jaragua',5270,'R. Cel. José Venâncio Dias, 840 - Jardim Nardini',''),
(66,'UniCEU Vila Curuçá','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Vila-Curuca--Polo-Jd-Miragaia',5270,'Av. Marechal Tito, 3.452 - Jardim Miragaia',''),
(67,'UniCEU Vila Rubi','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Cursos--UniCEU-Vila-Rubi',5270,'Rua Domingos Tarroso, 101 - Vila Rubi',''),
(68,'EMEF Gilberto Dupas','http://portal.sme.prefeitura.sp.gov.br/Main/Noticia/Visualizar/PortalSMESP/Curso--EMEF-Gilberto-Dupas--Polo-Vila-Nova-Cachoeirinha',5270,'Av. Dep. Emilio Carlos, 3.871 - Vl. Nova Cachoeirinha',''),
/*Fim UNICEU*/
(69,'UNINOVE -Associação Educacional Nove Julho - Santo Amaro ','http://www.uninove.br/unidade/santo-amaro/',5270,'Rua Amador Bueno, 389/491 - Santo Amaro',''),
(70,'UNASP - Centro Universitário Adventista São Paulo','http://unasp-sp.edu.br/',5270,'Estrada Itapecirica, 5859 - Jardim Iae',''),
(71,'UniÍtalo - Universidade Ítalo Brasileira - Santo Amaro','http://www.italo.com.br/campus-santo-amaro',5270,'Avenida João Dias, 2046 - Santo Amaro',''),
(72,'Faculdade - Hospital Israelita Albert Einstein - Morato','https://www.einstein.br/estrutura/unidades/morato',5270,'Avenida Professor Francisco Morato, 4.293 - Butantã',''),
(73,'Faculdade - Hospital Israelita Albert Einstein - Morumbi','https://www.einstein.br/estrutura/unidades/morumbi',5270,'Avenida Albert Einstein, 627/701 - Morumbi ',''),
(74,'Faculdade - Hospital Israelita Albert Einstein - Faria Lima','https://www.einstein.br/estrutura/unidades/faria-lima',5270,'Avenida Brigadeiro Faria Lima, 12º andar, 1188, - Jardim Paulistano',''),
(75,'Faculdade - Hospital Israelita Albert Einstein - Paulista','https://www.einstein.br/estrutura/unidades/paulista',5270,'Avenida Paulista, 37 – 15º andar - Bela Vi​sta',''),
(76,'Faculdade - Hospital Israelita Albert Einstein - Vila Mariana','https://www.einstein.br/estrutura/unidades/vila-mariana',5270,'Rua Madre Cabrini, 462 - Vila Mariana ',''),
/*FATEC*/
(77,'Fatec Ipiranga - Pastor Enéas Tognini','http://www.fatecipiranga.edu.br/',5270,'Rua Frei João, 59 - Ipiranga',''),
(78,'Fatec Itaquera - Prof. Miguel Reale','http://www.fatecitaquera.edu.br/',5270,'Avenida Eng. Ardevan Machado, s/n - Itaquera',''),
(79,'Fatec São Paulo','http://www.fatecsp.br/',5270,'Avenida Tiradentes, 615 - Bom Retiro',''),
(80,'Fatec Sebrae','https://fatecsebrae.wordpress.com/',5270,'Alameda Nothman, 598 - Campos Elíseos',''),
(81,'Fatec Tatuapé - Victor Civita','http://www.fatectatuape.edu.br/',5270,'Rua Antonio de Barros, 800 - Tatuapé',''),
(82,'Fatec Zona Leste','http://www.ctzl.edu.br/',5270,'Aenida Aguia de Haia, 2983 - Cidade A. E. Carvalho',''),
(83,'Fatec Zona Sul - Dom Paulo Evaristo Arns','http://www.fateczonasul.edu.br/',5270,'R. Frederico Grotte, 322 - Jd. São Luis','As Fatecs são importantes instituições brasileiras de ensino superior, sendo pioneiras na graduação de tecnólogos. É uma das seis instituições estaduais de educação superior mantidas pelo governo do estado de São Paulo no Brasil');
GO

SET IDENTITY_INSERT TB_UNIDADE_DE_ENSINO OFF;
GO